set serveroutput on
DECLARE
	OBJ1	OBJ_MAP02;
	OBJ2	OBJ_MAP02;
BEGIN
	OBJ1 := OBJ_MAP02(1,'TEST');
	OBJ2 := OBJ_MAP02_KO(2,'TEST2','ETST');
	DBMS_OUTPUT.PUT_LINE(OBJ1.DISPLAY2);
	DBMS_OUTPUT.PUT_LINE(OBJ2.DISPLAY2);
END;
/