-- 継承ｵﾌﾞｼﾞｪｸﾄの作成
-- 親ｻﾝﾌﾟﾙｵﾌﾞｼﾞｪｸﾄの作成
-- TYPEの作成
CREATE OR REPLACE TYPE OBJ_SAMPLE02_OYA AS OBJECT
(
	VAL1 NUMBER
	,VAL2 NUMBER
	,MEMBER PROCEDURE PRO01
	,MEMBER FUNCTION FNC01 RETURN NUMBER
) NOT FINAL;
/
-- TYPE BODYの作成
CREATE OR REPLACE TYPE BODY OBJ_SAMPLE02_OYA
AS
	MEMBER PROCEDURE PRO01
	IS
	BEGIN
		DBMS_OUTPUT.PUT_LINE('親ｵﾌﾞｼﾞｪｸﾄの処理です');
	END PRO01;
--
	MEMBER FUNCTION FNC01 RETURN NUMBER
	IS
	BEGIN
		RETURN VAL1 + VAL2;
	END FNC01;
END;
/
-- 子ｻﾝﾌﾟﾙｵﾌﾞｼﾞｪｸﾄの作成
CREATE OR REPLACE TYPE OBJ_SAMPLE02_KO UNDER OBJ_SAMPLE02_OYA
(
	MEMBER PROCEDURE PRO02
);
/
--
CREATE OR REPLACE TYPE BODY OBJ_SAMPLE02_KO
AS
	MEMBER PROCEDURE PRO02
	IS
	BEGIN
		DBMS_OUTPUT.PUT_LINE('子ｵﾌﾞｼﾞｪｸﾄの処理です');
	END PRO02;
END;
/
--
DECLARE
	OBJ OBJ_SAMPLE02_KO;
BEGIN
	OBJ := OBJ_SAMPLE02_KO(50,30);
	OBJ.PRO01;
	OBJ.PRO02;
END;
/

/** ｻﾝﾌﾟﾙｵﾌﾞｼﾞｪｸﾄの削除
	DROP TYPE OBJ_SAMPLE02_KO;
	DROP TYPE OBJ_SAMPLE02_OYA;
**/