-- »ÝÌßÙµÌÞ¼Þª¸Ä‚Ìì¬
-- TYPE‚Ìì¬
CREATE OR REPLACE TYPE OBJ_SAMPLE01 AS OBJECT
(
	VAL1 NUMBER
	,VAL2 NUMBER
	,MEMBER PROCEDURE PRO01
	,MEMBER FUNCTION FNC01 RETURN NUMBER
)
/
-- TYPE BODY‚Ìì¬
CREATE OR REPLACE TYPE BODY OBJ_SAMPLE01
AS
	MEMBER PROCEDURE PRO01
	IS
	BEGIN
		DBMS_OUTPUT.PUT_LINE('VAL1:' || VAL1 || ' VAL2:' || VAL2);
	END PRO01;
--
	MEMBER FUNCTION FNC01 RETURN NUMBER
	IS
	BEGIN
		RETURN VAL1 + VAL2;
	END FNC01;
END;
/
-- »ÝÌßÙˆ—‚ÌŽÀs
DECLARE
	OBJ OBJ_SAMPLE01;
BEGIN
	OBJ := OBJ_SAMPLE01(100,50);
	OBJ.PRO01;
	DBMS_OUTPUT.PUT_LINE('VAL1 + VAL2 = ' || OBJ.FNC01);
END;
/
/** »ÝÌßÙµÌÞ¼Þª¸Ä‚Ìíœ
DROP TYPE OBJ_SAMPLE01;
**/